[package]
name = "mentat-client"
version = "0.1.0"
edition = "2021"
rust-version = "1.62.1"

[dependencies]
anyhow = { workspace = true }
mentat-types = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
reqwest = { workspace = true }
