[package]
name = "mentat-constructor"
version = "0.1.0"
edition = "2021"
rust-version = "1.62.1"

[dependencies]
mentat-tokenizer = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
mentat-test-utils = { workspace = true }
