address = "0.0.0.0"
blockchain = "Bitcoin"
mode = "Online"
network = "Mainnet"
secure_http = false
node_address = "USER:PASS@127.0.0.1"
node_path = "D:\\Program Files\\Bitcoin\\daemon\\bitcoind.exe"
node_rpc_port = 3032
port = 8080
[custom]
user = "USER"
pass = "PASS"
data_dir = "D:\\files\\btc"