[package]
name = "mentat"
version = "0.1.0"
edition = "2021"
rust-version = "1.59.0"

[features]
_network = ["axum", "indexmap", "serde", "serde_json", "reqwest"]
client = ["_network"]
default = ["server"]
server = ["_network", "color-eyre", "opentelemetry", "opentelemetry-jaeger", "tokio", "tower", "tracing", "tracing-error", "tracing-opentelemetry", "tracing-subscriber", "tracing-tree"]

[dependencies]
axum = { version = "0.4.8", optional = true, default-features = false, features = ["http1", "json"] }
color-eyre = { version = "0.6.1", optional = true }
indexmap = { version = "1.7", optional = true, default-features = false, features = ["serde"] }
opentelemetry = { version = "0.17.0", optional = true, features = ["rt-tokio"] }
opentelemetry-jaeger = { version = "0.16.0", optional = true, features = ["rt-tokio"] }
serde = { version = "1.0", optional = true, default-features = false, features = ["derive"] }
serde_json = { version = "1.0", optional = true }
reqwest = { version = "0.11", optional = true, default-features = false, features = ["json"] }
tokio = { version = "1.17.0", optional = true, features = ["full"] }
tower = { version = "0.4.12", optional = true, default-features = false }
tracing = { version = "0.1.32", optional = true }
tracing-error = { version = "0.2.0", optional = true }
tracing-opentelemetry = { version = "0.17.2", optional = true }
tracing-subscriber = { version = "0.3.9", optional = true, features = ["env-filter"] }
tracing-tree = { version = "0.2.0", optional = true }
