address = "0.0.0.0"
blockchain = "Aleo"
mode = "Online"
network = "Testnet"
secure_http = false
node_address = "127.0.0.1"
node_path = "E:\\Work\\Aleo\\leo_repos\\snarkOS\\target\\release\\snarkos.exe"
node_rpc_port = 3032
port = 8080