name: CI
on:
  pull_request:
    push:
      branches:
        - main

env:
  RUST_BACKTRACE: 1

jobs:
  fmt:
    name: Check Clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Install Rust Stable
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Clippy Check
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all
